[project]
authors = ["Hannah Zafar <hannah.zafar@nasa.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "micasa_LPJ"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
xarray = ">=2025.11.0,<2026"
virtualizarr = ">=2.2.1,<3"
ipykernel = ">=7.1.0,<8"
netcdf4 = ">=1.7.3,<2"
h5netcdf = ">=1.7.3,<2"
matplotlib = ">=3.10.8,<4"
cartopy = ">=0.25.0,<0.26"
dask = ">=2025.11.0,<2026"
hvplot = ">=0.12.1,<0.13"
jupyter_bokeh = ">=4.0.5,<5"

[pypi-dependencies]
virtualizarr-nc4-toolkit = { git = "git+https://github.com/hannahzafar/virtualizarr-nc4-toolkit.git" }
